language: php

services:
  - postgresql
  - mysql

matrix:
  include:
    - php: 7.2
      env: ZEND_BACKEND="--backend=ZendEngine3"
    - php: 7.3
      env: ZEND_BACKEND="--backend=ZendEngine3"

git:
  depth: 1

cache:
  ccache: true
  timeout: 604800
  directories:
    - .temp
    - vendor
    - $HOME/.ccache
    - $HOME/.composer/cache
    - $HOME/cphalcon/$PHALCON_VERSION
    - $HOME/ext/$PHALCON_VERSION

env:
  global:
    - PATH="$PATH:~/bin"
    - DISPLAY=":99.0"
    - PHALCON_VERSION=v4.0.0-rc.2

before_install:
  - export PHP_VERSION=$(php-config --version)
  - export PHP_MAJOR="$(echo $TRAVIS_PHP_VERSION | cut -d '.' -f 1)"
  - export PHP_EXTENSION_DIR=$(php-config --extension-dir)
  - source $TRAVIS_BUILD_DIR/tests/_ci/environment
  - export $(cut -d= -f1 $TRAVIS_BUILD_DIR/tests/_ci/environment)
  - phpenv config-rm xdebug.ini || true
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com $GH_TOKEN; fi;
  - bash tests/_ci/setup_dbs.sh

install:
  - pecl install --force psr
  - .ci/install-phalcon.sh

before_script:
  - travis_retry composer install --no-interaction --no-ansi --no-progress --no-suggest
  - composer require --dev phpstan/phpstan
  - ln -s $PWD/phalcon ~/bin/phalcon

script:
  - mkdir .phalcon
  - vendor/bin/phpcs
  - vendor/bin/codecept build
  - vendor/bin/codecept run unit -v
  - vendor/bin/codecept run functional -v
  - vendor/bin/codecept run console -v
  - vendor/bin/psalm --show-info=false
  - vendor/bin/phpstan analyse -l 5 -c phpstan.neon scripts -v
