language: php

sudo: required

services:
  - postgresql
  - mysql

matrix:
  include:
    - php: 7.2
      env: ZEND_BACKEND="--backend=ZendEngine3"
    - php: 7.3
      env: ZEND_BACKEND="--backend=ZendEngine3"

git:
  depth: 1

cache:
  ccache: true
  timeout: 691200
  directories:
    - .temp
    - vendor
    - $HOME/.ccache
    - $HOME/.composer/cache
    - $HOME/cphalcon/$PHALCON_VERSION
    - $HOME/ext/$PHALCON_VERSION

env:
  global:
    - PATH="$PATH:~/bin"
    - DISPLAY=":99.0"
    - PHALCON_VERSION="v4.0.0-rc.1"

before_install:
  - export PHP_VERSION=$(php-config --version)
  - export PHP_MAJOR="$(echo $TRAVIS_PHP_VERSION | cut -d '.' -f 1)"
  - export PHP_EXTENSION_DIR=$(php-config --extension-dir)
  - source $TRAVIS_BUILD_DIR/tests/_ci/environment
  - export $(cut -d= -f1 $TRAVIS_BUILD_DIR/tests/_ci/environment)
  - phpenv config-rm xdebug.ini || true
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com $GH_TOKEN; fi;
  - git clone -q --branch $PHALCON_VERSION --depth=1 https://github.com/phalcon/cphalcon.git $HOME/cphalcon/$PHALCON_VERSION
  - bash tests/_ci/setup_dbs.sh

install:
  - if [ ! -f $HOME/ext/$PHALCON_VERSION/$PHP_VERSION/phalcon.so ]; then cd $HOME/cphalcon/$PHALCON_VERSION/build && bash ./install --phpize $(phpenv which phpize) --php-config $(phpenv which php-config) && mkdir -p $HOME/ext/$PHP_VERSION && cp $PHP_EXTENSION_DIR/phalcon.so $HOME/ext/$PHP_VERSION/phalcon.so; fi;
  - if [ -f $HOME/ext/$PHALCON_VERSION/$PHP_VERSION/phalcon.so ]; then cp $HOME/ext/$PHALCON_VERSION/$PHP_VERSION/phalcon.so $PHP_EXTENSION_DIR/phalcon.so; fi;
  - cd $TRAVIS_BUILD_DIR
  - travis_retry composer install --prefer-dist --no-interaction
  - if [ "$PHP_MAJOR" == "7" ]; then composer require --dev phpstan/phpstan:^0.9; fi;

before_script:
  - ln -s $PWD/phalcon ~/bin/phalcon

script:
  - vendor/bin/phpcs
  - vendor/bin/codecept build
  - vendor/bin/codecept run unit -v
  - vendor/bin/codecept run functional -v
  - vendor/bin/codecept run console -v
  - '[[ "$PHP_MAJOR" == "5" ]] || vendor/bin/phpstan analyse -l 5 -c phpstan.neon scripts -v'

notifications:
  email:
    recipients:
      - build@phalconphp.com
    on_success: change
    on_failure: always
